# Generated by Django 5.2.1 on 2025-05-24 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Piece',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=100)),
                ('designation', models.CharField(max_length=200)),
                ('volume', models.CharField(max_length=100)),
                ('material', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
                ('family', models.CharField(max_length=100)),
                ('group', models.CharField(max_length=100)),
                ('keywords', models.TextField()),
                ('image', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
